apiVersion: v2
name: datasqrl-sqrlpipeline
description: A Helm chart for datasqrl pipeline stack

type: application
version: 0.3.0
# Not used directly
appVersion: "1.16.0"

maintainers:
  - name: Tianchen
    email: tianchen@datasqrl.com
