engine:
  flink:
    version: "v1_19"
    enable_high_availability: false
    jobManager:
      resource:
        memory: "1g"
        cpu: 0.5
    taskManager:
      resource:
        memory: "1g"
        cpu: 0.5
    logging:
      format: json
      level: info
    flinkConfiguration:
      taskmanager.numberOfTaskSlots: "1"
      jobmanager.memory.process.size: "512m"
      taskmanager.memory.process.size: "512m"
      metrics.reporters: prom
      metrics.reporter.prom.factory.class: org.apache.flink.metrics.prometheus.PrometheusReporterFactory
      metrics.reporter.prom.port: "9249"
      metrics.reporter.prom.interval: 1 MINUTE
      # access public s3 bucket
      fs.s3a.aws.credentials.provider: org.apache.hadoop.fs.s3a.AnonymousAWSCredentialsProvider
  database:
    logging:
      level: info
  server:
    metrics:
      port: 8888
      path: "metrics"
