apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config-{{ include "sqrlpipeline.name_suffix" . }}
  labels:
    service: vertx
{{ include "sqrlpipeline.base_common_labels" . | indent 4 }}
data:
  server-config.json: |-
    {{ .Values.server_config_json | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-model-{{ include "sqrlpipeline.name_suffix" . }}
  labels:
    service: vertx
{{ include "sqrlpipeline.base_common_labels" . | indent 4 }}
data:
  server-model.json: |-
    {{ .Values.server_model_json | nindent 4 }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-envs-{{ include "sqrlpipeline.name_suffix" . }}
  labels:
    service: vertx
{{ include "sqrlpipeline.base_common_labels" . | indent 4 }}
data:
  {{- range .Values.engine.server.env_vars }}
   {{ .name }}: {{ .value | quote }}
  {{- end }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment-{{ include "sqrlpipeline.name_suffix" . }}
  labels:
    app: server
    service: vertx
{{ include "sqrlpipeline.base_common_labels" . | indent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
      short_id: {{ include "sqrlpipeline.short_id" . }}
  template:
    metadata:
      labels:
        app: server
        service: "vertx"
{{ include "sqrlpipeline.base_common_labels" . | indent 8 }}
    spec:
      initContainers:
        - name: copy-files
          image: busybox
          command: ['sh', '-c', 'cp /tmp/server-config/server-config.json /tmp/opt/sqrl/ && cp /tmp/server-model/server-model.json /tmp/opt/sqrl/']
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/opt/sqrl
            - name: server-config
              mountPath: /tmp/server-config
            - name: server-model
              mountPath: /tmp/server-model

      containers:
        - name: server
          image: {{ .Values.engine.server.image.name }}:{{ .Values.engine.server.image.tag }}
          workingDir: /opt/sqrl
          command: ["sh", "-c", "cp /tmp/opt/sqrl/* /opt/sqrl && java -jar vertx-server.jar"]
          envFrom:
            - configMapRef:
                name: server-envs-{{ include "sqrlpipeline.name_suffix" . }}
          ports:
            - containerPort: 8888
              name: graphql
            - containerPort: {{ .Values.engine.server.metrics.port }}
              name: metrics
          readinessProbe:
            httpGet:
              path: /health
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
          imagePullPolicy: Always
          volumeMounts:
            - name: shared-volume
              mountPath: /tmp/opt/sqrl
      
      volumes:
          - name: server-config
            configMap:
              name: server-config-{{ include "sqrlpipeline.name_suffix" . }}
          - name: server-model
            configMap:
              name: server-model-{{ include "sqrlpipeline.name_suffix" . }}
          - name: shared-volume
            emptyDir: {}