apiVersion: v1
kind: Service
metadata:
  name: server-service-{{ include "sqrlpipeline.name_suffix" . }}
  labels:
    service: vertx
{{ include "sqrlpipeline.base_common_labels" . | indent 4 }}
spec:
  selector:
    app: server
    short_id: {{ include "sqrlpipeline.short_id" . }}
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
  type: ClusterIP