name: Release Workflow

on:
  release:
    types: [published]

env:
  RELEASE_TAG: ${{ github.event.release.tag_name }}

jobs:
  prod-release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v4
        with:
          version: "v1.29.1"
        id: install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::286928876767:role/github-workflow-oidc-role-dev
          aws-region: us-east-1

      - name: Login ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | helm registry login --username AWS --password-stdin public.ecr.aws/j5u7a3j2

      - name: Package and publish namespace-dependencies
        working-directory: ./charts/namespace-dependencies
        run: |
          VERSION=${RELEASE_TAG#v}
          echo "publish namespace-dependencies at ${VERSION}"
          helm package . --version ${VERSION}
          helm push datasqrl-namespace-dependencies-${VERSION}.tgz oci://public.ecr.aws/j5u7a3j2

      - name: Package and publish sqrlpipeline
        working-directory: ./charts/sqrlpipeline
        run: |
          VERSION=${RELEASE_TAG#v}
          echo "publish sqrlpipeline at ${VERSION}"
          helm package . --version ${VERSION}
          helm push datasqrl-sqrlpipeline-${VERSION}.tgz oci://public.ecr.aws/j5u7a3j2
